name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
softdepend: ["PlaceholderAPI"]
api-version: 1.13
commands:
  tnttag:
    aliases: ["tnt"]
    description: "Main tnttag command"
  tnttagadmin:
    aliases: ["tntadmin", "tadmin", "tnta"]
    description: "Admin tnttag command"
